### ISSUE TITLE
Uri resolving errors

### ISSUE THREAD

**Issue by IAndreaGiuseppe** [tkr2f/uri-resolver#2]
Hi @tkr2f how is going? Thank you for this component 😄 

I'm using your resolver inside one of my package and I need you to inspect some assertions that should be valid but it's not.

Here is the list of tests that don't pass (in the form of a dataProvider for phpunit)

```php
    public function dataProvider()
    {
        // url - baseUri - expected
        return [
            ['#', 'http://localhost/bar/', 'http://localhost/bar/#'],

            ['?foo=2', 'http://localhost?foo=1', 'http://localhost?foo=2'],
            ['?bar=2', 'http://localhost?foo=1', 'http://localhost?bar=2'],
            ['/foo', 'file:///', 'file:///foo'],
            ['/foo', 'file:///bar/baz', 'file:///foo'],
            ['foo', 'file:///', 'file:///foo'],
            ['foo', 'file:///bar/baz', 'file:///bar/foo'],
        ];
    }
```

can you please take a look and resolve if necessary?
Thanks

**Comment by tkr2f** [comment]
As you pointed out, there was a problem resolving the "Same-Document Reference", so I fixed it.

https://github.com/tkr2f/uri-resolver/commit/6a868de114d98f559ac58ee733442921c5690816

And it has been released in v2.1.0

https://github.com/tkr2f/uri-resolver/releases/2.1.0

Thank you for reporting the issue and sorry for the late response.
